// Split data shared by the home panels and the four split pages.
window.SPLITS = [
  {
    slug: 'builder',
    num: '01',
    label: 'BUILDER',
    color: '#168BFF',
    tint: '#7fb8ff',
    rim: ['#168BFF', '#20D9FF'],
    bg: 'linear-gradient(170deg, #1b3352 0%, #12141f 72%)',
    teaser: 'Ships agents, MCP servers, and RAG pipelines that run in production.',
    headline: 'Ships agents, MCP servers, and RAG pipelines that run in production.',
    body: [
      'At UNT he builds AI agents that automate university workflows, written in Copilot Studio and NebulaOne, wired to Excel and Word through custom MCP servers he wrote himself, backed by RAG pipelines on Azure AI Foundry.',
      "Outside work: VoiceCode turns a patient's spoken symptoms into an Epic-compatible FHIR bundle. A fracture detector that shows its reasoning with Grad-CAM. A risk-evaluation harness for clinical LLM agents.",
      'On DenialDecoder he brought the original idea and built the React front end.',
    ],
    links: [{ label: 'GitHub ↗', href: 'https://github.com/samuel172002' }],
    images: [
      { src: 'img/builder.jpg', alt: 'Samuel in a denim jacket, arms crossed', caption: '', pos: '45% 35%', zoom: 1.32, origin: '56% 39%', mirror: true },
      { src: 'img/creator-02.jpg', alt: 'Samuel presenting the CareLens research poster at a UNT conference', caption: 'Presenting CareLens', pos: '30% 26%', mirror: false },
      { src: 'img/builder-02.jpg', alt: 'Samuel pointing at the CareLens poster on a conference board', caption: 'CareLens poster', pos: '26% 30%', mirror: false },
    ],
  },
  {
    slug: 'philanthropist',
    num: '02',
    label: 'PHILANTHROPIST',
    color: '#F13DFF',
    tint: '#f79aef',
    rim: ['#F13DFF', '#FF63D8'],
    bg: 'linear-gradient(170deg, #4a2a6e 0%, #12141f 72%)',
    teaser: 'Packs meals with the Lions Club. Builds tools that give people time back.',
    headline: "Shows up where the work isn't visible.",
    body: [
      'He volunteers with Feed My Starving Children alongside Lions Club members, packing meals for children overseas.',
      'On his 24th birthday he served food at Denton Freedom House, a rehabilitation center in Denton.',
      "The same instinct shows up in the code. NaviDoc exists to hand doctors back time they'd otherwise spend digging through records. His mental-health companion assesses wellbeing in five questions and surfaces crisis helpline information automatically the moment it detects risk.",
    ],
    links: [],
    images: [
      { src: 'img/philanthropist.jpg', alt: 'Samuel smiling and giving a thumbs up', caption: '', pos: '54% 33%', zoom: 1.1, origin: '85% 24%', mirror: false },
      { src: 'img/philanthropist-02.jpg', alt: 'Samuel with the Feed My Starving Children volunteer group in front of the session total: 14,688 meals packed', caption: '14,688 meals · FMSC', pos: '78% 40%', mirror: false },
      { src: 'img/philanthropist-03.jpg', alt: 'Samuel in a hairnet working the packing line at Feed My Starving Children', caption: 'On the packing line', pos: '72% 44%', mirror: false },
    ],
  },
  {
    slug: 'creator',
    num: '03',
    label: 'CREATOR',
    color: '#20D9FF',
    tint: '#8ce6ff',
    rim: ['#20D9FF', '#7B3CFF'],
    bg: 'linear-gradient(170deg, #14415a 0%, #12141f 72%)',
    teaser: '1,500+ followers. Reels from every conference. And a late-night AI show.',
    headline: 'Builds an audience the same way he builds software — in public.',
    body: [
      { pre: 'He makes content about AI for ', hi: '1,500+ followers on LinkedIn', post: " — reels from tech conferences, breakdowns of what he's learning, and field notes from the events he attends. It's the reason his network keeps growing faster than his résumé does." },
      "The newest thing is The Late Night AI Show — a late-night format built around artificial intelligence, written and shot by him. It's early. That's the point.",
    ],
    links: [
      { label: 'LinkedIn ↗', href: 'https://www.linkedin.com/in/samuel-sibbi-rayan-jerome-bbb8aa24a/' },
      { label: 'The Late Night AI Show ↗', href: 'https://www.youtube.com/@TheLateNightAIShow' },
    ],
    images: [
      { src: 'img/creator.jpg', alt: 'Samuel in a red checked flannel shirt', caption: '', pos: '55% 13%', zoom: 1.55, origin: '63% 3%', mirror: false },
      { src: 'img/creator-03.jpg', alt: 'Samuel mid-interview with a guest across the table on The Late Night AI Show', caption: 'The Late Night AI Show', pos: '50% 50%', fit: 'contain', mirror: false },
    ],
  },
  {
    slug: 'leader',
    num: '04',
    label: 'LEADER',
    color: '#7B3CFF',
    tint: '#b9a4ff',
    rim: ['#7B3CFF', '#F13DFF'],
    bg: 'linear-gradient(170deg, #2f2a6d 0%, #12141f 72%)',
    teaser: 'President of SSAI. Co-founded a startup at 21 and ran its operations.',
    headline: 'President of SSAI. Co-founded a startup at 21 and ran its operations.',
    body: [
      'President of the Society for Student AI Innovation at UNT since July 2026, after seven months as Vice President. He runs strategic planning for student-led AI initiatives, coordinates the executive board, and goes to outside conferences specifically to find real industry projects students can work on.',
      "Before that he co-founded Sentient Matters in Chennai, an AI-operated news outlet, and served as COO for over a year. It became the first incubatee at India's first AI Technology Business Incubator.",
      "He ran operations, marketing, and finance, reviewed AI-curated news for accuracy before publication, and spoke on GenAI at St. Joseph's College of Engineering, Sathyabama Institute, and the InnovAI conference at the Indian Institute of Management.",
    ],
    links: [],
    images: [
      { src: 'img/leader.jpg', alt: 'Samuel in a black suit and tie', caption: '', pos: '51% 32%', zoom: 1.05, origin: '61% 30%', mirror: false },
      { src: 'img/leader-02.jpg', alt: 'Samuel and the SSAI officers at the club recruitment table in Discovery Park', caption: 'SSAI · Discovery Park', pos: '24% 46%', mirror: false },
      { src: 'img/leader-03.jpg', alt: 'Samuel beside the AI Horizons 2026 conference banner at the Gateway Center', caption: 'AI Horizons 2026', pos: '76% 52%', mirror: false },
    ],
  },
];
